version: '3'

env:
  DISPLAY: ':2'

tasks:
  test:
    cmds:
      - cargo test -- --nocapture

  cap:
    cmds:
      - cargo test

  trace:
    env:
      RUST_BACKTRACE: 1
    cmds:
      - cargo test

  test-*:
    vars:
      MOD: '{{index .MATCH 0}}'
    cmds:
      - cargo test {{.MOD}}_test -- --include-ignored

  cap-*:
    vars:
      MOD: '{{index .MATCH 0}}'
    cmds:
      - cargo test {{.MOD}}_test -- --no-capture --include-ignored

  debug:
    cmds:
      - cargo run -- -d {{.DISPLAY}} --replace --debug {{.CLI_ARGS}}

  valgrind:
    aliases: [v]
    cmds:
      - cargo valgrind run -- -d {{.DISPLAY}} --replace {{.CLI_ARGS}}

  run:
    cmds:
      - cargo run -- -d {{.DISPLAY}} {{.CLI_ARGS}}

  clean:
    cmds:
      - cargo clean

  background:
    aliases: [bg]
    cmds:
      - xsetroot -d {{.DISPLAY}} -solid "#595959"

  alacritty:
    aliases: [a]
    cmds:
      - zsh -c "DISPLAY={{.DISPLAY}} alacritty &"

  xephyr:
    aliases: [x]
    cmds:
      - |
        Xephyr -ac -noreset +extension RANDR +xinerama -name xeph640 \
          -screen 640x480 -resizeable -reset {{.DISPLAY}} &
      - sleep 2 && xsetroot -d {{.DISPLAY}} -solid "#595959"

  tray:
    cmds:
      - yad --notification

  release:
    cmds:
      - cargo build --release

  pkglist:
    cmds:
      - cargo package --list
