version: '3'

env:
  DISPLAY: ':2'
  ARGS: '--config-file=./debug.toml {{.CLI_ARGS}}'

includes:
  battery:
    taskfile: plugins/battery/Taskfile.yml
    dir: plugins/battery

  fuzzytime:
    taskfile: plugins/fuzzytime/Taskfile.yml
    dir: plugins/fuzzytime

  mem:
    taskfile: plugins/mem/Taskfile.yml
    dir: plugins/mem

  time:
    taskfile: plugins/time/Taskfile.yml
    dir: plugins/time

tasks:
  # Test helpers
  test:
    cmds:
      - cargo test -- --nocapture

  cap:
    cmds:
      - cargo test

  trace:
    env:
      RUST_BACKTRACE: 1
    cmds:
      - cargo test

  test-*:
    vars:
      MOD: '{{index .MATCH 0}}'
    cmds:
      - cargo test {{.MOD}}_test -- --include-ignored

  cap-*:
    vars:
      MOD: '{{index .MATCH 0}}'
    cmds:
      - cargo test {{.MOD}}_test -- --no-capture --include-ignored

  # Debug helpers
  debug:
    cmds:
      - cargo run -- -d {{.DISPLAY}} --replace --debug {{.ARGS}}

  valgrind:
    aliases: [v]
    cmds:
      - cargo valgrind run -- -d {{.DISPLAY}} --replace {{.ARGS}}

  # Cargo helpers
  release:
    cmds:
      - cargo build --release

  pkglist:
    cmds:
      - cargo package --list

  doc:
    cmds:
      - cargo doc

  doctest:
    cmds:
      - cargo test --doc

  run:
    cmds:
      - cargo run -- -d {{.DISPLAY}} {{.ARGS}}

  clean:
    cmds:
      - cargo clean

  bloat:
    cmds:
      - cargo bloat

  # Tool helpers
  background:
    aliases: [bg]
    cmds:
      - xsetroot -d {{.DISPLAY}} -solid "#595959"

  alacritty:
    aliases: [a]
    cmds:
      - zsh -c "DISPLAY={{.DISPLAY}} alacritty &"

  xephyr:
    aliases: [x]
    cmds:
      - zsh -c "Xephyr -ac -noreset +extension RANDR +xinerama -name xeph640 -screen 640x480 -resizeable -reset {{.DISPLAY}} &>/dev/null &"

  tray:
    cmds:
      - yad --notification
