version: '3'

tasks:
  test:
    cmds:
      - cargo test -- --nocapture

  cap:
    cmds:
      - cargo test

  trace:
    env:
      RUST_BACKTRACE: 1
    cmds:
      - cargo test

  run:
    cmds:
      - cargo run -- {{.CLI_ARGS}}

  clean:
    cmds:
      - cargo clean
