version: '3'

env:
  DISPLAY: ':2'

tasks:
  test:
    cmds:
      - cargo test -- --nocapture

  cap:
    cmds:
      - cargo test

  trace:
    env:
      RUST_BACKTRACE: 1
    cmds:
      - cargo test

  debug:
    cmds:
      - cargo run -- -d {{.DISPLAY}} --replace --debug {{.CLI_ARGS}}

  run:
    cmds:
      - cargo run -- -d {{.DISPLAY}} {{.CLI_ARGS}}

  clean:
    cmds:
      - cargo clean

  background:
    cmds:
      - xsetroot -d {{.DISPLAY}} -solid "#595959"
